# Generated by Django 3.2.9 on 2021-11-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('d', 'Disponible'), ('nd', 'No disponible')], default='Disponible', help_text='Disponibilidad', max_length=14)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parking.cliente')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.plaza')),
            ],
        ),
    ]
