# Generated by Django 3.2.9 on 2021-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_cliente_plaza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('tipo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('altura', models.IntegerField()),
                ('anchura', models.IntegerField()),
                ('largura', models.IntegerField()),
            ],
        ),
    ]
