# Generated by Django 3.2.9 on 2021-12-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_plaza_dimensiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parking.plaza', unique=True),
        ),
        migrations.AlterField(
            model_name='dimensiones',
            name='anchura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='dimensiones',
            name='largura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
